### ISSUE TITLE
Ears

### ISSUE THREAD

**Issue by jhasse** [nasa42/rust-libs#8]
Hi!

I've made a fork of ears which works with newer versions of Rust and has some other fixes: https://github.com/jhasse/ears

It's also available via Cargo: https://crates.io/crates/ears/

Can you change the link? Because https://github.com/JeremyLetang/ears doesn't even compile with Rust 1.0 and isn't maintained anymore.

(I've also [asked JeremyLetang](https://github.com/jeremyletang/ears/issues/11#issuecomment-179519231), but no response yet)

**Comment by nasa42** [comment]
Fixed. Thanks!
